//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StaffManagementEntities : DbContext
    {
        public StaffManagementEntities()
            : base("name=StaffManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoomRestaurant> RoomRestaurants { get; set; }
        public virtual DbSet<SalaryPosition> SalaryPositions { get; set; }
        public virtual DbSet<StaffRestaurant> StaffRestaurants { get; set; }
    }
}
