//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomRestaurant
    {
        public RoomRestaurant()
        {
            this.SalaryPositions = new HashSet<SalaryPosition>();
            this.StaffRestaurants = new HashSet<StaffRestaurant>();
        }
    
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public string Position { get; set; }
    
        public virtual ICollection<SalaryPosition> SalaryPositions { get; set; }
        public virtual ICollection<StaffRestaurant> StaffRestaurants { get; set; }
    }
}
