//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRestaurant
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phonenumber { get; set; }
        public string Address { get; set; }
        public Nullable<int> Room_Id { get; set; }
    
        public virtual RoomRestaurant RoomRestaurant { get; set; }
    }
}
